services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  backend:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
    env_file:
      - .env

  worker:
    build: .
    command: celery -A app.tasks worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - rabbitmq
      - backend
    env_file:
      - .env
    restart: always
