
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
  
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - celery_exporter

  celery_exporter:
    image: danihodovic/celery-exporter
    command: >
      --broker-url=${CELERY_BROKER_URL} 
      --retry-interval=5
    env_file: .env
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
    ports:
      - "9808:9808"
    depends_on:
      rabbitmq:
        condition: service_healthy

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana


  backend:
    build: .
    command: sh -c "python db/seed.py && uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 6"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      rabbitmq:
        condition: service_healthy
      kafka:
        condition: service_healthy
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 5s
      timeout: 3s
      retries: 3

  worker:
    build: .
    environment:
      - RUN_PROM_METRICS=true
      - PROMETHEUS_MULTIPROC_DIR=/tmp/prometheus_multiproc_dir
    ports:
      - "8005:8005"
    command: >
      sh -c " rm -rf /tmp/prometheus_multiproc_dir/* &&
        mkdir -p /tmp/prometheus_multiproc_dir &&
        celery -A "app.tasks:app" worker \
          --loglevel=info \
          -Q webhook_q_0,webhook_q_1,webhook_q_2,webhook_q_3 \
          --concurrency=8
      "
    volumes:
      - .:/code
    depends_on:
      rabbitmq:
        condition: service_healthy
      kafka:
        condition: service_started
      backend:
        condition: service_started
    env_file:
      - .env
    restart: always

  dlq_consumer:
    build: .
    command: python -m app.kafka.dlq_consumer
    depends_on:
      - kafka
    env_file:
      - .env
    restart: on-failure

  test_runner:
    build: .
    depends_on:
      - backend
      - kafka
      - rabbitmq
      - worker
      - prometheus
      - celery_exporter
    env_file:
      - .env
volumes:
  grafana-storage:

